//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATCNC.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATCNC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 首先欢迎使用本软件！
        ///
        ///本软件是中国科学院研究生院内部使用的网络认证客户端，由C#开发完成，因此支持流行的全部Windows操作系统，只需要保证安装了.NET Framework 2.0即可。本软件使用美观图形界面，具有使用简单、安装方便、功能强大等优点，是院内网络认证客户端的首选！
        ///
        ///本软件为开放源代码软件，遵从GPL协议。您可以在此协议下自由地使用、修改或分发本软件。软件开发过程中得到了实验室王佳宾同学的协助，本软件的开发思想是由Solrex Yang师兄的CASNET项目所激发的，在此表示感谢。
        ///
        ///使用本软件过程中有任何疑问，或报告存在的bug，欢迎联系我，电子邮件：jiang.cedric@gmail.com。 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首先欢迎使用本客户端软件！
        ///
        ///程序启动后，并不弹出窗口，而主要通过任务栏右侧的通知区图标操作。右击图标弹出功能菜单，左键双击图标执行流量查询功能。
        ///
        ///首次使用请先填写登录信息，您需要选择登录域，一般来说，学生选择mails.gucas.ac.cn，教工选择gucas.ac.cn，然后填写用户名和密码并保存。以后也可以修改此信息，但修改后下次连接时才生效。
        ///
        ///您可以对软件功能进行设置，这些设置和登录信息都保存在注册表中，其中密码是以明文形式保存的，请注意尽量不要使用您的常用密码作为上网密码，以防别人从注册表中偷窥到您的密码。
        ///
        ///本软件模拟了网页登录的方式。由于使用了SSL协议(https)，所以在登录过程中不会泄露您的密码等信息，安全性非常有保障。但此种方式登录时可能有若干秒的延时，应该在可接受的范围之内。
        ///
        ///本软件提供启动软件后自动连接的功能，考虑到常用情况，自动连接时连线的是国际模式，如需要连线其它模式请手工选择。
        ///
        ///研究生院模式是为流量和金额提醒功能设置的，指研究生一年级的免费使用2G国内和1G国际流量的使用模式，非研究生院模式即为25元每月使用5G国内和2G国际流量的使用模式。本 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Offline {
            get {
                object obj = ResourceManager.GetObject("Offline", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Online {
            get {
                object obj = ResourceManager.GetObject("Online", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
